# Generated by Django 5.1.6 on 2025-02-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subdomain_prefix", models.CharField(max_length=255, unique=True)),
                ("db_volume_size", models.CharField(max_length=10)),
                ("tenant_namespace", models.CharField(max_length=50, unique=True)),
                ("config_map_reference", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
