# Generated by Django 5.1.6 on 2025-02-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="resource_status",
            field=models.CharField(
                choices=[("not_created", "Not Created"), ("ready", "Ready")],
                default="not_created",
                max_length=20,
            ),
        ),
    ]
