# Generated by Django 5.1.6 on 2025-02-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0002_tenant_resource_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="backend_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
