apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-service
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}-app
