{{- if .Values.backendApp.configMapReference }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backendApp.configMapReference.refName }}
data:
{{- range $key, $value := .Values.backendApp.configMapReference.values }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
