apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tenant-charts
  namespace: flux-system
spec:
  url: "https://ribonred.github.io/k8s-tenant-exercise"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgresql-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-system
