apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.saas.com
  namespace: tenant-system
spec:
  group: saas.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tenantName:
                type: string
              domain:
                type: string
              dbVolumeSize:
                type: string
              tenantNamespace:
                type: string
              configMapReference:
                type: object
                required: [ "refName" ] # Ensure refName is always present
                properties:
                  refName:
                    type: string
                  values:
                    type: object
                    additionalProperties:
                      type: string
  scope: Namespaced
  names:
    plural: tenants
    singular: tenant
    kind: Tenant
    shortNames:
    - tenant
